version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bitcoin_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bitcoin_db"]
      interval: 5s
      retries: 5
      timeout: 3s

  app:
    build: ./frontend
    container_name: nuxt_app
    restart: always
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://user:password@database:5432/bitcoin_db

volumes:
  pgdata:
